# Generated by Django 5.2.5 on 2025-08-30 12:35

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('PENDING', 'Pending Review'), ('SCHEDULED', 'Review Scheduled'), ('FEEDBACK', 'Feedback Provided'), ('APPROVAL', 'Under Approval'), ('APPROVED', 'Review Approved'), ('REJECTED', 'Review Rejected')], default='PENDING', max_length=50, protected=True)),
                ('feedback', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='organizations.employee')),
            ],
        ),
    ]
